version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
  settings:
    gocyclo:
      min-complexity: 25

run:
  timeout: 5m
