version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15

run:
  timeout: 5m
  go: '1.25'
